export const RoutePath = {
  HOME_PATH: "/",
  PRODUCT_PATH: "/product",
  PRODUCT_LIST_PATH: "/product/list",
  PRODUCT_VARIANTS_PATH: "/product/variants",
  PRODUCT_ORDER_PATH: "/product/order",
  PRODUCT_PURCHASE_ORDERS_PATH: "/product/purchase-orders",
  PRODUCT_CHECK_GOODS_PATH: "/product/check-goods",
  PRODUCT_SHIPPING_PATH: "/product/shipping",
  PRODUCT_SUPPLIER_PATH: "/product/supplier",
  PRODUCT_CAPPITAL_PRICE_ADJUSTMENT_PATH: "/product/capital-price-adjustment",
  ORDER_PATH: "/order",
  ORDER_CREATE_PATH: "/order/create",
  ORDER_LIST_PATH: "/order/list",
  ORDER_CUSTOMER_PAYS_PATH: "/order/customer-pays",
  CLIENT_PATH: "/client",
  CLIENT_LIST_PATH: "/client/list",
  CLIENT_CUSTOMER_GROUP_PATH: "/client/customer-group",
  SELLING_COUNTER_PATH: 'selling-counter'
};
